// COMIC ACTIONS
export const COMIC_GET_LATEST = "COMIC_GET_LATEST";
export const COMIC_GET_LATEST_PENDING = "COMIC_GET_LATEST_PENDING";
export const COMIC_GET_LATEST_SUCCESS = "COMIC_GET_LATEST_SUCCESS";
export const COMIC_GET_LATEST_FAIL = "COMIC_GET_LATEST_FAIL";
